### ISSUE TITLE
Where did TSS's for hg38 go?

### ISSUE THREAD

**Issue by jpsmith5** [databio/GenomicDistributionsData#5]
This has always been working previously. 
```
refAssembly <- "hg38"
getReferenceData(refAssembly, tagline = "TSS_")
```
I recently tested the most recent versions and now this command gives:
```
TSS_hg38 not available in GenomicDistributions and GenomicDistributionsData packages
```
But strangely, calling TSS_hg38() finds it correctly. And testing with TSS_hg19() works. Then setting refAssembly to "hg19", the getReferenceData call works. So am I just missing a change in the command usage? This breaks several plots in the pipelines so would be happy to know what the solution is if someone has insight.

**Comment by kkupkova** [comment]
This is strange. It works for me just fine. And I have the latest versions installed.

**Comment by nsheff** [comment]
what was the answer?

**Comment by jpsmith5** [comment]
It was how you install GenomicDistributionsData within the container or virtual environment. If it's not installed directly from the tar.gz file it gives the misleading error. In the Dockerfile it was installing via devtools::install_github() which causes this error to arise.

**Comment by nsheff** [comment]
ah. Yeah, install_github can't work for this package because it would be missing the actual data

**Comment by jpsmith5** [comment]
Yeah that was on me. I even do it the correct way with install guides but hadn’t tested bulker from a fresh install or as ‘—strict’ to find the issue with the rpipe container
