### ISSUE TITLE
TSS_mm10 SourceURL

### ISSUE THREAD

**Issue by ChristelKrueger** [databio/GenomicDistributionsData#8]
Hi there
In https://github.com/databio/GenomicDistributionsData/blob/master/inst/extdata/metadata.csv the source URL for TSS_mm10 is given as https://bioconductor.org/packages/release/data/annotation/html/TxDb.Mmusculus.UCSC.mm9.knownGene.html
Is this just a typo in the metadata table or are the annotations indeed from the mm9 genome?
Thanks, Christel

**Comment by joseverdezoto** [comment]
Dear Christel,

Thanks for catching this. That is indeed a typo in the metadata table, which has now been fixed.

**Comment by ChristelKrueger** [comment]
Thanks!
