### ISSUE TITLE
failed to load resource

### ISSUE THREAD

**Issue by yyang-SDI** [databio/GenomicDistributionsData#9]
Hi,
I have posted this issue at https://github.com/Bioconductor/ExperimentHub/issues/33 but this seems to be a more appropriate repo? 

I am trying to get the TSS_mm10 using `TSSmm10 = hub[["EH3479"]]` or `ep = calcExpectedPartitionsRef(query, "mm10") `and end up getting these errors:

Error: failed to load resource
name: EH3479
title: TSS_mm10
reason: 1 resources failed to download
In addition: Warning messages:
1: download failed
web resource path: 'https://experimenthub.bioconductor.org/fetch/3495'
local file path: '/Users/yyang/Library/Caches/org.R-project.R/R/ExperimentHub/43cb7c5335c7_3495'
reason: Conflict (HTTP 409).
2: bfcadd() failed; resource removed
rid: BFC32
fpath: 'https://experimenthub.bioconductor.org/fetch/3495'
reason: download failed
3: download failed
hub path: 'https://experimenthub.bioconductor.org/fetch/3495'
cache resource: 'EH3479 : 3495'
reason: bfcadd() failed; see warnings()

I also tried to `wget https://experimenthub.bioconductor.org/fetch/3491` and getting this error in terminal too:

--2023-10-17 23:04:10-- https://experimenthub.bioconductor.org/fetch/3491
Resolving experimenthub.bioconductor.org (experimenthub.bioconductor.org)... 52.73.93.102
Connecting to experimenthub.bioconductor.org (experimenthub.bioconductor.org)|52.73.93.102|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://bioconductorhubs.blob.core.windows.net/experimenthub/GenomicDistributionsData/data/chromSizes_mm10.rda [following]
--2023-10-17 23:04:11-- https://bioconductorhubs.blob.core.windows.net/experimenthub/GenomicDistributionsData/data/chromSizes_mm10.rda
Resolving bioconductorhubs.blob.core.windows.net (bioconductorhubs.blob.core.windows.net)... 20.209.52.97, 20.209.53.161, 20.60.62.97
Connecting to bioconductorhubs.blob.core.windows.net (bioconductorhubs.blob.core.windows.net)|20.209.52.97|:443... connected.
HTTP request sent, awaiting response... 409 Public access is not permitted on this storage account.
2023-10-17 23:04:11 ERROR 409: Public access is not permitted on this storage account..

Any idea how to get access to this file?

Thanks!

**Comment by kkupkova** [comment]
Hi! 

There seems to be an issue with ExperimentHub (I saw the exact same report for another dataset from another package today, let's hope it's temporary). I will monitor the issue. Before it gets fixed an alternative is building the references directly from GTF and FASTA files - you don't even need to download those, just provide URL. [Here](https://kkupkova.github.io/GenomicDistributionsBioC2022/articles/GenomicDistributions_vignette.html#j--custom-reference) is a tutorial that guides you to build all your reference data (and shows you how to use it with all calculation functions) with GenomicDistributions. Sorry that I cannot offer you a better solution at this point.

**Comment by kloot** [comment]
I'm seeing the same issue (from RStudio/Win10)
Is there a another way to download the ZhaoImmuneLiverData() set as SingleCellExperiment object (acknowledging that it's not related to GenomicsDistribution)?
Thanks in advance!

```
Warning: download failed
  web resource path: 'https://experimenthub.bioconductor.org/fetch/5388'
  local file path: 'C:\Users\KL3900X\AppData\Local/R/cache/R/ExperimentHub/67504927528e_5388'
  reason: Conflict (HTTP 409).Warning: bfcadd() failed; resource removed
  rid: BFC6
  fpath: 'https://experimenthub.bioconductor.org/fetch/5388'
  reason: download failedWarning: download failed
  hub path: 'https://experimenthub.bioconductor.org/fetch/5388'
  cache resource: 'EH5345 : 5388'
  reason: bfcadd() failed; see warnings()Error: failed to load resource
  name: EH5345
  title: Zhao immune liver counts
  reason: 1 resources failed to download
```

**Comment by kkupkova** [comment]
As you mentioned, this is not an issue relevant to GenomicDistributionsData, you will have to contact creators of ZhaoImmuneLiverData dataset.

**Comment by kloot** [comment]
I don't think it is an issue with the ZhaoImmuneLiverData because the same error occurs with other datasets in ExperimentHub.
Although it may be unrelated to GenomicDistributions, I reported it because @yyang-SDI reported a similar problem a few hours earlier with GenomicDistributions, so I wonder whether both GenomicDistributions and ExperimentHub share the same (troubled) infrastructure?

**Comment by kkupkova** [comment]
> I don't think it is an issue with the ZhaoImmuneLiverData because the same error occurs with other datasets in ExperimentHub. Although it may be unrelated to GenomicDistributions, I reported it because @yyang-SDI reported a similar problem a few hours earlier with GenomicDistributions, so I wonder whether both GenomicDistributions and ExperimentHub share the same (troubled) infrastructure?

And exactly like ZhaoImmuneLiverData, GenomicDistributions has nothing to do with this problem. The data package (GenomicDistributionsData) uses ExperimentHub that seems to be experiencing issues.

**Comment by kkupkova** [comment]
> Hi, I have posted this issue at [Bioconductor/ExperimentHub#33](https://github.com/Bioconductor/ExperimentHub/issues/33) but this seems to be a more appropriate repo?
> 
> I am trying to get the TSS_mm10 using `TSSmm10 = hub[["EH3479"]]` or `ep = calcExpectedPartitionsRef(query, "mm10") `and end up getting these errors:
> 
> Error: failed to load resource name: EH3479 title: TSS_mm10 reason: 1 resources failed to download In addition: Warning messages: 1: download failed web resource path: 'https://experimenthub.bioconductor.org/fetch/3495' local file path: '/Users/yyang/Library/Caches/org.R-project.R/R/ExperimentHub/43cb7c5335c7_3495' reason: Conflict (HTTP 409). 2: bfcadd() failed; resource removed rid: BFC32 fpath: 'https://experimenthub.bioconductor.org/fetch/3495' reason: download failed 3: download failed hub path: 'https://experimenthub.bioconductor.org/fetch/3495' cache resource: 'EH3479 : 3495' reason: bfcadd() failed; see warnings()
> 
> I also tried to `wget https://experimenthub.bioconductor.org/fetch/3491` and getting this error in terminal too:
> 
> --2023-10-17 23:04:10-- https://experimenthub.bioconductor.org/fetch/3491 Resolving experimenthub.bioconductor.org (experimenthub.bioconductor.org)... 52.73.93.102 Connecting to experimenthub.bioconductor.org (experimenthub.bioconductor.org)|52.73.93.102|:443... connected. HTTP request sent, awaiting response... 302 Found Location: https://bioconductorhubs.blob.core.windows.net/experimenthub/GenomicDistributionsData/data/chromSizes_mm10.rda [following] --2023-10-17 23:04:11-- https://bioconductorhubs.blob.core.windows.net/experimenthub/GenomicDistributionsData/data/chromSizes_mm10.rda Resolving bioconductorhubs.blob.core.windows.net (bioconductorhubs.blob.core.windows.net)... 20.209.52.97, 20.209.53.161, 20.60.62.97 Connecting to bioconductorhubs.blob.core.windows.net (bioconductorhubs.blob.core.windows.net)|20.209.52.97|:443... connected. HTTP request sent, awaiting response... 409 Public access is not permitted on this storage account. 2023-10-17 23:04:11 ERROR 409: Public access is not permitted on this storage account..
> 
> Any idea how to get access to this file?
> 
> Thanks!

I got an e-mail today confirming that ExperimentHub and AnnotationHub are experiencing issues. So please keep checking or use the alternative approach I posted above based on creating your own annotation objects from FASTA and GTF files.

**Comment by yyang-SDI** [comment]
Thank you for the help!
